version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: soundclone_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=soundclone
      - POSTGRES_PASSWORD=soundclone
  adminer:
    image: adminer
    container_name: soundclone_adminer
    ports:
      - '8080:8080'
  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: soundclone_mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
  redis:
    container_name: soundclone_redis
    image: redis
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: soundclone_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
