# Generated by Django 4.2.3 on 2023-07-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="waveform",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="version",
            name="waveform",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
