# Generated by Django 4.2.2 on 2023-07-19 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Album",
            new_name="Playlist",
        ),
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ("playlist", "order")},
        ),
        migrations.RenameField(
            model_name="song",
            old_name="album",
            new_name="playlist",
        ),
    ]
