# Generated by Django 4.2.3 on 2023-07-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_song_waveform_version_waveform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs",
                to="core.playlist",
            ),
        ),
    ]
