# Generated by Django 4.2.3 on 2023-08-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_song_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="preview_file",
            field=models.FileField(
                blank=True, null=True, upload_to="songs/preview/%Y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="preview_file",
            field=models.FileField(
                blank=True, null=True, upload_to="songs/versions_preview/%Y/%m/%d"
            ),
        ),
    ]
